avenirs-esr/avenirs-cofolio-client

.husky/pre-commit
.idea/inspectionProfiles/Project_Default.xml
.idea/jsLinters/eslint.xml
eslint.config.js
package-lock.json
package.json

✨ configure lint-staged for automatic linting of staged files
💄 set up ESLint and Prettier checks to run before commit
🔧 update pre-commit hook to trigger linting on relevant files
🔧 run tests before pushing

build(119): configure lint staged

---

src/components.d.ts
src/ui/cards/AvCard/AvCard.vue
src/ui/cards/AvSkillCard/AvSkillCard.test.ts
src/ui/cards/AvSkillCard/AvSkillCard.vue
src/ui/cards/AvSkillCard/index.ts
src/ui/cards/index.ts
src/ui/styles/palette.scss
src/ui/styles/typography.scss
src/ui/tokens/icons.ts

- :sparkles: add AvSkillCard
- :bento: add AvSkillAcademicIcon
- :lipstick: add colors and typographies
- :art: clean code
---
- https://github.com/avenirs-esr/AVENIRS-Project/issues/102
---
- master
---
---
---
**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.
Please do not submit a pull request to ask questions.
Do not submit pull requests without tests …

feat(102): create AvSkillCard

---

src/features/student/components/StudentNavigation.vue
src/features/student/components/StudentProfileModal.vue

---
- :speech_balloon: update literals
---
- master
---

feat: update literals

---

src/features/student/components/StudentCourseSkillsContainer.vue
src/features/student/components/index.ts
src/types/api-types.ts
src/types/index.ts
src/ui/cards/AvSkillCard/AvSkillCard.test.ts
src/ui/cards/AvSkillCard/AvSkillCard.vue
src/ui/cards/AvSkillCard/index.ts
src/ui/styles/palette.scss
src/ui/styles/typography.scss

---
- :sparkles: add StudentCourseSkillsContainer
- :lipstick: update palette and typographies
- 🏷️ add api-types.ts (should be overwritten with a swagger)
---
- https://github.com/avenirs-esr/AVENIRS-Project/issues/104
---
- master
---
---

feat(104): create student course skills container

---

src/assets/main.css
src/features/student/components/containers/StudentCourseSkillsContainer.vue
src/features/student/components/containers/index.ts
src/features/student/components/index.ts
src/features/student/components/widgets/StudentCoursesSkillsWidget.vue
src/features/student/components/widgets/index.ts
src/features/student/views/StudentHomeView.vue
src/ui/cards/AvCard/AvCard.vue
src/ui/styles/palette.scss
src/ui/styles/typography.scss

---
- :sparkles: add StudentCoursesSkillsWidget
- :sparkles: implement StudentCoursesSkillsWidget in StudentHomeView with mocked data
- :lipstick: add backgroundColor prop to AvCard
- :lipstick: remove top and bottom margins from all h
- :lipstick: add colors and typographies
- :art: clean code
---
- https://github.com/avenirs-esr/AVENIRS-Project/issues/103
---
- master
---
- 1 course with 8 skills
- 2 courses with 8 skills each
---

feat(103): create courses skills widget

---

src/common/composables/use-navigation.ts
src/features/student/components/widgets/StudentSkillsWidget.vue
src/features/student/components/widgets/index.ts
src/features/student/views/StudentHomeView.vue
src/ui/tokens/icons.ts

- :sparkles: StudentSkillsWidget - add see all skills CTA
- ✨ add navigation to skills in useNavigation composable
- 🚚 rename StudentCoursesSkillsWidget to StudentSkillsWidget
- :bento: update right arrow icon
---
- https://github.com/avenirs-esr/AVENIRS-Project/issues/106
---
- master
---
[Capture vidéo du 2025-05-14 14-31-27.webm](https://github.com/user-attachments/assets/1787bd98-77b7-4505-a1f0-75330cf317fc)
---
---

feat(106): StudentSkillsWidget - add see all skills CTA

---

package-lock.json
package.json
src/features/student/views/StudentHomeView.vue
src/i18n.ts
src/locales/en.json
src/locales/fr.json
src/main.ts
src/ui/cards/AvSkillCard/AvSkillCard.test.ts
src/ui/cards/AvSkillCard/AvSkillCard.vue
src/utils/tests/index.ts
src/utils/tests/mountWithI18n.ts

---
- :heavy_plus_sign: add vue-i18n (11.1.3)
- 💬 implement one text to test it
- ✅ update AvSkillCard unit tests to work with i18n
---
- https://github.com/avenirs-esr/AVENIRS-Project/issues/130
---
- master
---
---
---
Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

feat(130): add vue-i18n

---

src/features/student/components/cards/StudentSkillCard/StudentSkillCard.test.ts
src/features/student/components/cards/StudentSkillCard/StudentSkillCard.types.ts
src/features/student/components/cards/StudentSkillCard/StudentSkillCard.vue
src/features/student/components/cards/StudentSkillCard/index.ts
src/features/student/components/cards/index.ts
src/features/student/components/containers/StudentSkillsWidgetContainer.vue
src/features/student/components/index.ts
src/features/student/locales/en.json
src/features/student/locales/fr.json
src/locales/en.json
src/locales/fr.json
src/plugins/vue-i18n.ts
src/ui/cards/AvSkillCard/index.ts
src/ui/cards/index.ts
vitest-setup.ts

---
- ♻️ AvSkillCard - rename to StudentSkillCard and move it to student components
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/140
---
- master
---
---

refactor(140): AvSkillCard - rename to StudentSkillCard and move it to student components

---

src/common/utils/date.ts
src/features/student/components/cards/StudentSkillCard/StudentSkillCard.vue
src/features/student/components/cards/StudentTrackCard/StudentTrackCard.test.ts
src/features/student/components/cards/StudentTrackCard/StudentTrackCard.types.ts
src/features/student/components/cards/StudentTrackCard/StudentTrackCard.vue
src/features/student/components/cards/StudentTrackCard/index.ts
src/features/student/components/cards/index.ts
src/features/student/components/widgets/StudentResumesWidget.vue
src/ui/cards/AvTrackCard/index.ts
src/ui/cards/index.ts

---
- ♻️ AvTrackCard - rename to StudentTrackCard and move it to student components
- :speech_balloon: fix typos
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/141
---
- master
---
---

refactor(141): AvTrackCard - rename to StudentTrackCard and move it to student components

---

package-lock.json
src/features/student/components/widgets/StudentSkillsWidget.vue
src/features/student/queries/use-student-summary.query.ts
src/features/student/views/StudentHomeView.vue

✨ Fonctionnalité : Ajout du résumé des cours l'étudiant avec TanStack Query
Ticket lié : https://github.com/avenirs-esr/AVENIRS-Project/issues/143
✅ Nouveautés
Intégration de TanStack Query pour récupérer et mettre en cache efficacement les données du résumé des cours d'un étudiant.
🧪 Tests effectués
Vérification du bon chargement et du cache des données.
Validation de la mise à jour réactive de l’interface lors des changements de données.
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/143

feat(143): add student courses summary query

---

src/common/composables/use-navigation.ts
src/common/utils/date.ts
src/features/student/components/cards/StudentSkillCard/StudentSkillCard.vue
src/features/student/components/cards/StudentTrackCard/StudentTrackCard.vue
src/features/student/components/widgets/StudentEventsWidget.vue
src/features/student/components/widgets/StudentPagesWidget.vue
src/features/student/components/widgets/index.ts
src/features/student/locales/en.json
src/features/student/locales/fr.json
src/features/student/routes.ts
src/features/student/views/StudentEventsView.vue
src/features/student/views/StudentHomeView.vue
src/types/api-types.ts
src/ui/interaction/buttons/AvRichButton/AvRichButton.types.ts
src/ui/interaction/buttons/AvRichButton/AvRichButton.vue
src/ui/styles/palette.scss
src/ui/styles/typography.scss

---
- :sparkles: add StudentEventsWidget
- :sparkles: implement StudentEventsWidget into StudentHomeView
- :hammer: add student events navigation
- :art: add date handlers
- :speech_balloon: add translations
- :lipstick: update typography and palette
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/142
---
- master
---
- FR
- EN
---

feat(142): create StudentEventsWidget

---

a11y/student.a11y.spec.ts
src/common/components/PageTitle.vue
src/common/components/index.ts
src/common/composables/use-navigation.ts
src/components.d.ts
src/features/student/components/modals/StudentMailboxModal.vue
src/features/student/locales/en.json
src/features/student/locales/fr.json
src/features/student/routes.ts
src/features/student/views/StudentEducationActivitiesView.vue
src/features/student/views/StudentEducationSkillsView.vue
src/features/student/views/StudentMailboxView.vue
src/features/student/views/StudentMessagesView.vue
src/features/student/views/StudentNotificationsView.vue
src/features/student/views/StudentProjectSkillsView.vue
src/features/student/views/StudentProjectTrajectoriesView.vue
src/features/student/views/StudentToolsPagesView.vue
src/features/student/views/StudentToolsResumesView.vue
src/features/student/views/StudentToolsTracksView.vue
src/locales/en.json
src/locales/fr.json
src/ui/interaction/buttons/AvButton/AvButton.vue
src/ui/styles/links.scss
src/ui/styles/main.scss
src/ui/styles/typography.scss
src/ui/tokens/icons.ts

---
- :sparkles: add PageTitle (breadcrumb, goback btn, title) to all views
- :lipstick: add typography
- :recycle: rename messages to mailbox
- :bento: add icons
- :speech_balloon: add i18n translations
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/145
---
- master
---
[Capture vidéo du 2025-05-20 11-09-18.webm](https://github.com/user-attachments/assets/0210d2d6-77ec-45d6-8af4-8b2b394140c7)
---
---

feat(145): add PageTitle (breadcrumb, goback btn, title) to all views

---

src/features/student/components/widgets/StudentResumesWidget.vue
src/features/student/queries/use-student-summary.query.ts
src/features/student/views/StudentHomeView.vue

✨ Fonctionnalité : Ajout du résumé des CV l'étudiant avec TanStack Query
[Ticket lié : https://github.com/avenirs-esr/AVENIRS-Project/issues/143](https://github.com/avenirs-esr/AVENIRS-Project/issues/152)
✅ Nouveautés
Intégration de TanStack Query pour récupérer et mettre en cache efficacement les données du résumé des cours d'un étudiant.
🧪 Tests effectués
Vérification du bon chargement et du cache des données.
Validation de la mise à jour réactive de l’interface lors des changements de données.
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/152

feat(152): add student resumes summary

---

src/common/composables/use-navigation.ts
src/features/student/components/widgets/StudentDeliverablesWidget.vue
src/features/student/components/widgets/StudentPagesWidget.vue
src/features/student/components/widgets/StudentResumesWidget.vue
src/features/student/components/widgets/index.ts
src/features/student/locales/en.json
src/features/student/locales/fr.json
src/features/student/queries/use-student-summary.query.ts
src/features/student/routes.ts
src/features/student/views/StudentDeliverablesView.vue
src/features/student/views/StudentHomeView.vue
src/types/api-types.ts
src/ui/interaction/buttons/AvRichButton/AvRichButton.vue
src/ui/styles/main.scss
src/ui/styles/texts.scss

---
- :sparkles: create StudentDeliverablesWidget and add it to StudentHomeView
- :sparkles: add placeholder StudentDeliverablesView and update StudentEventsView
- :hammer: update navigation et student queries
- :art: AvRichButton - improve ellipsis
- :speech_balloon: update i18n translations
- :label: update api types
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/153
---
- master
---
- FR
- EN
---
---
---

feat(153): create StudentDeliverablesWidget

---

src/features/student/components/cards/StudentSkillCard/StudentSkillCard.types.ts
src/features/student/components/cards/StudentSkillCard/StudentSkillCard.vue
src/features/student/locales/en.json
src/features/student/locales/fr.json
src/features/student/routes.ts
src/features/student/views/StudentSkillView.vue
src/ui/styles/links.scss

---
- :sparkles: StudentSkillCard - add correct onClick navigation
- :sparkles: add StudentSkillView placeholder
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/167
---
- master
---
[Capture vidéo du 2025-05-21 12-46-49.webm](https://github.com/user-attachments/assets/88339675-98b6-4689-a31d-b0ff7f4e80ca)
---
---

feat(167): StudentSkillCard - add correct onClick navigation

---

src/features/student/components/cards/StudentSkillCard/StudentSkillCard.vue
src/features/student/components/containers/StudentSkillsWidgetContainer.vue
src/features/student/components/widgets/StudentSkillsWidget.vue
src/features/student/queries/use-student-summary.query.ts
src/features/student/views/StudentHomeView.vue

---
- :lipstick: StudentSkillCard - truncate skill name at 3 lines
- :lipstick: StudentSkillsWidget - truncate course name at 60 characters
- :lipstick: StudentSkillsWidget - alphabetically sort skills and courses
- :lipstick: StudentSkillsWidget - only display widget if courses is not empty
- :bug: StudentHomeView - add import StudentTracksWidget
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/166
---
- master
---
---
**DO NOT** keep this template as is when you submit. Please remove or adjust the …

feat(166): StudentSkillsWidget - update display order and add conditional display

---

src/features/student/components/modals/StudentMailboxModal.vue
src/features/student/components/modals/StudentNotificationsModal.vue
src/ui/interaction/buttons/AvButton/AvButton.test.ts
src/ui/interaction/buttons/AvButton/AvButton.types.ts
src/ui/interaction/buttons/AvButton/AvButton.vue

- :white_check_mark: AvButton - full test coverage
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/168
---
- master
---
---

test(168): AvButton - complete covage

---

package.json
src/ui/header/AvHeader/AvHeader.test.ts
src/ui/header/AvHeader/AvHeader.vue
vitest.config.ts

---
- :white_check_mark: AvHeader - complete unit test coverage
- :art: AvHeader - remove unnecessary code
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/169
---
- master
---
- 3 funcs are missing from the tests : % Funcs: 70%, everything else at 100%
- Lines 224 to 229
```js
<template v-if="languageSelector">
<DsfrLanguageSelector
v-bind="languageSelector"
@select="languageSelector.currentLanguage = $event.codeIso"
/>
</template>
```
This one : …

test(168): AvHeader - complete unit test coverage

---

src/common/composables/index.ts
src/common/composables/use-toaster/index.ts
src/common/composables/use-toaster/use-toaster.test.ts
src/common/composables/use-toaster/use-toaster.ts
src/features/student/layouts/StudentLayout.vue
src/features/teacher/layouts/TeacherLayout.vue

---
- :white_check_mark: add unit test coverage for useToaster
- :art: update architecture for useToaster
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/175
---
- master
---
---

test(175): add unit test coverage for useToaster

---

src/features/student/components/widgets/StudentEventsWidget/StudentEventsWidget.test.ts
src/features/student/components/widgets/StudentEventsWidget/StudentEventsWidget.vue
src/features/student/queries/use-student-summary.query.ts
src/features/student/views/StudentHomeView.vue

---
- :white_check_mark: add unit tests for StudentEventsWidget
- :recycle: add useStudentEventsSummaryQuery
- :bug: fix endDate display
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/183
---
- master
---
---

test(183): add unit tests for StudentEventsWidget

---

src/features/student/components/widgets/StudentOverviewWidget/StudentOverviewWidget.test.ts
src/features/student/components/widgets/StudentOverviewWidget/StudentOverviewWidget.vue
src/features/student/views/StudentHomeView.vue

---
- :white_check_mark: add unit tests for StudentOverviewWidget
- :recycle: move useStudentSummaryQuery into StudentOverviewWidget
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/184
---
- master
---
---

test(184): add unit tests for StudentOverviewWidget

---

src/features/student/components/widgets/StudentResumesWidget/StudentResumesWidget.test.ts
src/features/student/queries/use-student-summary.query.ts

---
- :white_check_mark: add unit tests for StudentResumesWidget
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/190
---
- master
---
---

test(190): add unit tests for StudentResumesWidget

---

src/bootstrap.test.ts
src/bootstrap.ts
src/main.ts

---
- :white_check_mark: add unit tests for main.ts (by testing bootstrap.ts)
- :recycle: update architecture
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/238
---
- master
---
---

test(238): add unit tests for main ts

---

src/features/student/queries/fixtures.ts
src/features/student/queries/use-ams-view.query/use-ams-view.query.test.ts
src/features/student/queries/use-ams-view.query/use-ams-view.query.ts

🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.
Thanks again for your work! 💪
Thank you for your contributions to CoFolio.
When you publish the pull request, please check off relevant items below in the description of your pull request.
---
---
Fixes https://github.com/avenirs-esr/AVENIRS-Project/issues/287
---
> _Detail any updates made to documentation, configuration steps, or technical specs._
---
---
> _Include any relevant context, technical details, or reasons …

feat(287): ams view endpoint implementation

---

src/common/composables/index.ts
src/common/composables/use-toast/use-toast.test.ts
src/common/composables/use-toast/use-toast.ts
src/common/composables/use-tosat/use-toast.ts
src/features/student/components/widgets/StudentDeliverablesWidget/StudentDeliverablesWidget.test.ts
src/features/student/components/widgets/StudentDeliverablesWidget/StudentDeliverablesWidget.vue
src/features/student/components/widgets/StudentEventsWidget/StudentEventsWidget.test.ts
src/features/student/components/widgets/StudentEventsWidget/StudentEventsWidget.vue
src/features/student/components/widgets/StudentOverviewWidget/StudentOverviewWidget.test.ts
src/features/student/components/widgets/StudentOverviewWidget/StudentOverviewWidget.vue
src/features/student/components/widgets/StudentPagesWidget/StudentPagesWidget.test.ts
src/features/student/components/widgets/StudentPagesWidget/StudentPagesWidget.vue
src/features/student/components/widgets/StudentResumesWidget/StudentResumesWidget.test.ts
src/features/student/components/widgets/StudentResumesWidget/StudentResumesWidget.vue
src/features/student/components/widgets/StudentSkillsWidget/StudentSkillsWidget.test.ts
src/features/student/components/widgets/StudentSkillsWidget/StudentSkillsWidget.vue
src/features/student/components/widgets/StudentTracesWidget/StudentTracesWidget.test.ts
src/features/student/components/widgets/StudentTracesWidget/StudentTracesWidget.vue
src/features/student/layouts/StudentLayout/StudentLayout.test.ts
src/features/student/layouts/StudentLayout/StudentLayout.vue
src/features/student/views/StudentEducationSkillsView/StudentEducationSkillsView.test.ts
src/features/student/views/StudentEducationSkillsView/StudentEducationSkillsView.vue
src/locales/en.json
src/locales/fr.json
tests/mocks/index.ts
tests/mocks/toaster.ts
tests/mocks/vueQueryError.ts
tests/utils.ts

---
- :sparkles: add error toast to queries
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/296
---
- master
---
> _List any limitations, known bugs, or side effects this PR may introduce._
- testUseBaseApiExceptionToast is not done for StudentLayout due to a failing test not failing in all other components
```
FAIL  src/features/student/layouts/StudentLayout/StudentLayout.test.ts > studentLayout > should add error message on query error
AssertionError: expected "spy" to be called at least once
❯ tests/utils.ts:85:33
83|     await flushPromises()
84| 
85| …
```

feat(296): add error toast to queries

---

api-specs/avenir-esr.swagger.json
src/api/avenir-esr/index.ts
src/features/student/components/badges/StudentLevelBadge/StudentLevelBadge.vue
src/features/student/components/widgets/StudentSkillsWidget/components/StudentSkillCard/StudentSkillCard.vue
src/features/student/queries/fixtures.ts
src/features/student/queries/use-program-progress-view.query/use-program-progress-view.query.ts
src/features/student/views/StudentEducationSkillsView/StudentEducationSkillsView.test.ts
src/features/student/views/StudentEducationSkillsView/components/StudentDetailedSkillCard/StudentDetailedSkillCard.vue
src/features/student/views/StudentEducationSkillsView/components/StudentEducationSkillsViewContainer/StudentEducationSkillsViewContainer.vue
src/types/api-types.ts

Replace mocked types with types generated from orval for program progress view.
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/285

build(285): replaced program progress types

---

src/features/student/queries/fixtures.ts
src/features/student/queries/use-student-configuration.query/use-student-configuration.query.test.ts
src/features/student/queries/use-student-configuration.query/use-student-configuration.query.ts
src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.test.ts
src/types/api-types.ts

🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.
Thanks again for your work! 💪
Thank you for your contributions to CoFolio.
When you publish the pull request, please check off relevant items below in the description of your pull request.
---
---
Fixes https://github.com/avenirs-esr/AVENIRS-Project/issues/282
---
> _Detail any updates made to documentation, configuration steps, or technical specs._
---
master
---
> _Include any relevant context, technical details, or …

feat(282): add traces config query

---

src/features/student/queries/fixtures.ts
src/features/student/queries/use-ams-view.query/use-ams-view.query.test.ts
src/features/student/queries/use-ams-view.query/use-ams-view.query.ts
src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.test.ts
src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.vue
src/features/student/views/StudentToolsTracesView/StudentToolsTracesView.test.ts
tests/mocks/ams.ts
tests/mocks/index.ts

---
- :bug: update useAmsViewQuery to match useUnassignedTracesViewQuery
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/318
---
- master
---
---

fix(318): update useAmsViewQuery

---

src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.test.ts
src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.vue
src/features/student/views/StudentEducationAmsView/components/StudentEducationAmsViewContainer/StudentEducationAmsViewContainer.test.ts
src/features/student/views/StudentEducationAmsView/components/StudentEducationAmsViewContainer/StudentEducationAmsViewContainer.vue

---
- :sparkles: add pagination to StudentEducationAmsView
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/294
---
- master
---
[Capture vidéo du 2025-06-23 15-34-52.webm](https://github.com/user-attachments/assets/16680fd7-a84b-42c8-b60d-48514c8fbf9a)
---
---
**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.
Please do not submit a pull …

feat(294): add pagination to StudentEducationAmsView

---

src/features/student/locales/en.json
src/features/student/locales/fr.json
src/features/student/views/StudentEducationAmsView/StudentEducationAmsView.vue
src/features/student/views/StudentEducationAmsView/components/AmsListContainer/AmsListContainer.test.ts
src/features/student/views/StudentEducationAmsView/components/AmsListContainer/AmsListContainer.vue
src/features/student/views/StudentEducationAmsView/components/AmsPlanningContainter/AmsPlanningContainer.test.ts
src/features/student/views/StudentEducationAmsView/components/AmsPlanningContainter/AmsPlanningContainer.vue
src/features/student/views/StudentEducationAmsView/components/AmsViewTabs/AmsViewTabs.test.ts
src/features/student/views/StudentEducationAmsView/components/AmsViewTabs/AmsViewTabs.vue
src/features/student/views/StudentEducationAmsView/components/StudentDetailedAmsCard/StudentDetailedAmsCard.vue
src/ui/interaction/tabs/AvTab/AvTab.test.ts
src/ui/interaction/tabs/AvTabs/AvTabs.test.ts
src/ui/tokens/icons.ts

---
- :sparkles: add AvTabs to StudentEducationAmsView
- :construction: add a placeholder AmsPlanningContainer
- :recycle: rename some components for integration
- :speech_balloon: update translations
- :bento: update icons
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/324
---
- master
---
[Capture vidéo du 2025-06-25 08-53-00.webm](https://github.com/user-attachments/assets/6fb0e99d-1e61-4c70-9a07-824e3d768214)
---
Please make sure you have addressed the following before …

feat(324): add AvTabs to StudentEducationAmsView

---

src/features/student/locales/fr.json

- :speech_balloon: fix an error in translation
---
- closes https://github.com/avenirs-esr/AVENIRS-Project/issues/356
---
- master
---
---
**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.
Please do not submit a pull request to ask questions.
Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

fix(356): update wrong translation in StudentDetailedAmsCard
